/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TituloPrueba.java
 *
 * Created on 06/08/2010, 11:24:31
 */

package visLotes;

/**
 *
 * @author Pablazo
 */
public class TituloPrueba extends javax.swing.JPanel {

    /** Creates new form TituloPrueba */
    public TituloPrueba() {
        initComponents();
    }

    public void setTitulo(String t){
        titulo.setText(t);
    }

//    public void setIntento(String t){
//        jlblIntento.setText(t);
//    }

    public void setDatos(String t){
        archivo.setText(t);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jlblTitulo = new javax.swing.JLabel();
        jlblDatos = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        archivo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dilacion = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jlblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlblTitulo.setText("Title: ");
        jlblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        add(jlblTitulo, gridBagConstraints);

        jlblDatos.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlblDatos.setText("File: ");
        jlblDatos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        add(jlblDatos, gridBagConstraints);

        titulo.setFont(new java.awt.Font("Tahoma", 0, 12));
        titulo.setPreferredSize(new java.awt.Dimension(400, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(titulo, gridBagConstraints);

        archivo.setFont(new java.awt.Font("Tahoma", 0, 12));
        archivo.setPreferredSize(new java.awt.Dimension(400, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 30.0;
        add(archivo, gridBagConstraints);

        jLabel1.setText("Dilation:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Weight:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        add(jLabel2, gridBagConstraints);

        dilacion.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        add(dilacion, gridBagConstraints);

        peso.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        add(peso, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel archivo;
    private javax.swing.JLabel dilacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlblDatos;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel peso;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    void setArchivo(String d) {
        archivo.setText(d);
    }
    
    void setDilacion(String d){
        dilacion.setText(d);
    }
    
    void setPeso(String p){
        peso.setText(p);
    }

}
