/*
 * FV.java
 *
 * Created on 6 de septiembre de 2009, 21:03
 */
package visualizador;

/**
 *
 * @author  Paola
 */
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.Locale;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;
import javax.swing.*;
import visLotes.VentanaPruebas;

public class FV extends javax.swing.JFrame {

    static JFrame ventana;
    static Conjunto l;
    private static Properties properties;
    private static String propertyFileName = "visLotes/Directorio.txt";

    static Dimension getSizeArea() {
        return jScrollPane1.getSize();
    }

    public static void cargarDesdeLote(Configuracion configuracion) {
        panel.cargarDesdeLote(configuracion);
    }

    public static void setTriangulationSelected(int tipo) {
        switch (tipo) {//por si llaman desde los botones
            case 1:
                jcbTDelaunay.setSelected(true);
                break;
            case 2:
                jcbTDivAndConq.setSelected(true);
                break;
            case 3:
                jcbTFan.setSelected(true);
                break;
            case 4:
                jcbTIncremental.setSelected(true);
                break;
            case 5:
                jcbTGreedy.setSelected(true);
                break;
        }
    }
    
    public static void setPseudoTriangulationSelected(int tipo) {
        switch (tipo) {//por si llaman desde los botones
            case 1:
                jcbPTRandom.setSelected(true);
                break;
            case 2:
                jcbPTSmallest.setSelected(true);
                break;
            case 3:
                jcbPTHighest.setSelected(true);
                break;
        }
    }
    
    public static void setPoligonizationSelected(int tipo) {
        switch (tipo) {//por si llaman desde los botones
            case 1:
                jcbS1.setSelected(true);
                break;
            case 2:
                jcbS2.setSelected(true);
                break;
            case 3:
                jcbS3.setSelected(true);
                break;
            case 4:
                jcbS4.setSelected(true);
                break;
            case 5:
                jcbS5.setSelected(true);
                break;
            case 6:
                jcbS6.setSelected(true);
                break;
        }
    }

    static void setFlipar(boolean selected) {
        jcbFlip.setSelected(selected);
    }
    
    static void setHabilitarFlipar(boolean selected) {
        jcbFlip.setEnabled(selected);
    }

    static void setDilacion(boolean selected) {
        jcbDilation.setSelected(selected);
    }

    static void setVoronoi(boolean selected) {
        jcbVoronoi.setSelected(selected);
    }

    static void setXY(boolean selected) {
        //jcbCoordinates.setSelected(selected);
    }

    static void setShowImage(boolean selected) {
        jcbShowBGImage.setSelected(selected);
    }

    static void setShowImagePunto(boolean b) {
        jcbShowImagePoints.setSelected(b);
    }

    static void setPintar(boolean b) {
        jcbPainTriangles.setSelected(b);
    }

    /** Creates new form FV */
    public FV() {
        l = new Conjunto();
        initComponents();
        //jcbVoronoi.addActionListener(new BotonListener());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGPT = new javax.swing.ButtonGroup();
        btnGT = new javax.swing.ButtonGroup();
        btnGP = new javax.swing.ButtonGroup();
        panelSur1 = new visualizador.PanelSur();
        panelNorte2 = new visualizador.PanelNorte();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new visualizador.JPanelDibujo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jcbDilation = new javax.swing.JCheckBoxMenuItem();
        jcbIsPT = new javax.swing.JMenuItem();
        jcbFlip = new javax.swing.JCheckBoxMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jcbTDelaunay = new javax.swing.JCheckBoxMenuItem();
        jcbTFan = new javax.swing.JCheckBoxMenuItem();
        jcbTGreedy = new javax.swing.JCheckBoxMenuItem();
        jcbTIncremental = new javax.swing.JCheckBoxMenuItem();
        jcbTDivAndConq = new javax.swing.JCheckBoxMenuItem();
        jcbVoronoi = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jcbPTRandom = new javax.swing.JCheckBoxMenuItem();
        jcbPTSmallest = new javax.swing.JCheckBoxMenuItem();
        jcbPTHighest = new javax.swing.JCheckBoxMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jcbS1 = new javax.swing.JCheckBoxMenuItem();
        jcbS2 = new javax.swing.JCheckBoxMenuItem();
        jcbS3 = new javax.swing.JCheckBoxMenuItem();
        jcbS4 = new javax.swing.JCheckBoxMenuItem();
        jcbS5 = new javax.swing.JCheckBoxMenuItem();
        jcbS6 = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jcbShowBGImage = new javax.swing.JCheckBoxMenuItem();
        jcbShowImagePoints = new javax.swing.JCheckBoxMenuItem();
        jcbPainTriangles = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("visualization toolbox");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        getContentPane().add(panelSur1, java.awt.BorderLayout.PAGE_END);

        panelNorte2.setPreferredSize(new java.awt.Dimension(300, 658));
        getContentPane().add(panelNorte2, java.awt.BorderLayout.WEST);

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 700));

        panel.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jScrollPane1.setViewportView(panel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem13.setText("Load points");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuItem14.setText("Load edges");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuItem2.setText("Load background image");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem12.setText("Load point image");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem3.setText("Save points and edges");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem22.setText("Save image");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem22);

        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Draw");

        jMenuItem6.setText("Add Point");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem10.setText("Add randomly Points");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem7.setText("Add Edge");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Remove Point");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Remove Edge");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem21.setText("Random Triangulation");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem21);

        jMenuBar1.add(jMenu2);

        jMenu9.setText("Calculate");

        jMenuItem17.setText("Convex hull");
        jMenu9.add(jMenuItem17);

        jcbDilation.setText("Dilation");
        jcbDilation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDilationActionPerformed(evt);
            }
        });
        jMenu9.add(jcbDilation);

        jcbIsPT.setText("is PseudoTirangulation?");
        jcbIsPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbIsPTActionPerformed(evt);
            }
        });
        jMenu9.add(jcbIsPT);

        jcbFlip.setText("Flip");
        jcbFlip.setEnabled(false);
        jcbFlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFlipActionPerformed(evt);
            }
        });
        jMenu9.add(jcbFlip);

        jMenuItem18.setText("Convex polygon");
        jMenu9.add(jMenuItem18);

        jMenuItem19.setText("Minimum area triangle");
        jMenu9.add(jMenuItem19);

        jMenuBar1.add(jMenu9);

        jMenu3.setText("Triangulation");

        btnGT.add(jcbTDelaunay);
        jcbTDelaunay.setText("Delaunay");
        jcbTDelaunay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTDelaunayActionPerformed(evt);
            }
        });
        jMenu3.add(jcbTDelaunay);

        btnGT.add(jcbTFan);
        jcbTFan.setText("Fan");
        jcbTFan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTFanActionPerformed(evt);
            }
        });
        jMenu3.add(jcbTFan);

        btnGT.add(jcbTGreedy);
        jcbTGreedy.setText("Greedy");
        jcbTGreedy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTGreedyActionPerformed(evt);
            }
        });
        jMenu3.add(jcbTGreedy);

        btnGT.add(jcbTIncremental);
        jcbTIncremental.setText("Incremental");
        jcbTIncremental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTIncrementalActionPerformed(evt);
            }
        });
        jMenu3.add(jcbTIncremental);

        btnGT.add(jcbTDivAndConq);
        jcbTDivAndConq.setText("Divide and Conquest");
        jcbTDivAndConq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTDivAndConqActionPerformed(evt);
            }
        });
        jMenu3.add(jcbTDivAndConq);

        jcbVoronoi.setText("Voronoi diagram");
        jcbVoronoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVoronoiActionPerformed(evt);
            }
        });
        jMenu3.add(jcbVoronoi);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("PseudoTriangulation");

        btnGPT.add(jcbPTRandom);
        jcbPTRandom.setText("Random");
        jcbPTRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPTRandomActionPerformed(evt);
            }
        });
        jMenu4.add(jcbPTRandom);

        btnGPT.add(jcbPTSmallest);
        jcbPTSmallest.setText("Smallest distance");
        jcbPTSmallest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPTSmallestActionPerformed(evt);
            }
        });
        jMenu4.add(jcbPTSmallest);

        btnGPT.add(jcbPTHighest);
        jcbPTHighest.setText("Highest distance");
        jcbPTHighest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPTHighestActionPerformed(evt);
            }
        });
        jMenu4.add(jcbPTHighest);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Poligonization");

        btnGP.add(jcbS1);
        jcbS1.setText("RandomGreedyTriangle - GreedyPoint - GreedyEdge (S1)");
        jcbS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbS1ActionPerformed(evt);
            }
        });
        jMenu7.add(jcbS1);

        btnGP.add(jcbS2);
        jcbS2.setText("RandomGreedyTriangle - RandomPoint - GreedyEdge (S2)");
        jcbS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbS2ActionPerformed(evt);
            }
        });
        jMenu7.add(jcbS2);

        btnGP.add(jcbS3);
        jcbS3.setText("RandomGreedyTriangle - GreedyArea (S3)");
        jcbS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbS3ActionPerformed(evt);
            }
        });
        jMenu7.add(jcbS3);

        btnGP.add(jcbS4);
        jcbS4.setText("RandomTriangle - GreedyPoint - GreedyEdge (S4)");
        jcbS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbS4ActionPerformed(evt);
            }
        });
        jMenu7.add(jcbS4);

        btnGP.add(jcbS5);
        jcbS5.setText("RandomTriangle - RandomPoint - GreedyEdge (S5)");
        jcbS5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbS5ActionPerformed(evt);
            }
        });
        jMenu7.add(jcbS5);

        btnGP.add(jcbS6);
        jcbS6.setText("RandomTriangle - GreedyArea (S6)");
        jcbS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbS6ActionPerformed(evt);
            }
        });
        jMenu7.add(jcbS6);

        jMenuBar1.add(jMenu7);

        jMenu5.setText("Options");

        jcbShowBGImage.setText("Show background image");
        jcbShowBGImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbShowBGImageActionPerformed(evt);
            }
        });
        jMenu5.add(jcbShowBGImage);

        jcbShowImagePoints.setText("Show image points");
        jcbShowImagePoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbShowImagePointsActionPerformed(evt);
            }
        });
        jMenu5.add(jcbShowImagePoints);

        jcbPainTriangles.setText("Paint triangles");
        jcbPainTriangles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPainTrianglesActionPerformed(evt);
            }
        });
        jMenu5.add(jcbPainTriangles);

        jMenuItem1.setText("Clear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("Simulations");

        jMenuItem11.setText("Init");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuBar1.add(jMenu8);

        jMenu6.setText("Help");

        jMenuItem26.setText("Help contents");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem26);

        jMenuItem28.setText("Web page");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem28);

        jMenuItem27.setText("About");
        jMenu6.add(jMenuItem27);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        panel.cargarImagenFondo(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        borrar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        //System.exit(1);
        salir(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        panelNorte2.agregarPunto();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        panelNorte2.aleatorio();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        panelNorte2.agregarArista();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        panelNorte2.borrarPunto();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        panelNorte2.borrarArista();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jcbTDelaunayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTDelaunayActionPerformed
        // TODO add your handling code here:
        //panelNorte2.delaunay();
        panelNorte2.triangular(1);
    }//GEN-LAST:event_jcbTDelaunayActionPerformed

    private void jcbTFanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTFanActionPerformed
        // TODO add your handling code here:
        //panelNorte2.fan();
        panelNorte2.triangular(3);
    }//GEN-LAST:event_jcbTFanActionPerformed

    private void jcbTGreedyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTGreedyActionPerformed
        // TODO add your handling code here:
        //panelNorte2.greedy();
        panelNorte2.triangular(5);
    }//GEN-LAST:event_jcbTGreedyActionPerformed

    private void jcbTIncrementalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTIncrementalActionPerformed
        // TODO add your handling code here:
        //panelNorte2.incremental();
        panelNorte2.triangular(4);
    }//GEN-LAST:event_jcbTIncrementalActionPerformed

    private void jcbTDivAndConqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTDivAndConqActionPerformed
        // TODO add your handling code here:
        //panelNorte2.divide();
        panelNorte2.triangular(2);
    }//GEN-LAST:event_jcbTDivAndConqActionPerformed

    private void jcbPTRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPTRandomActionPerformed
        // TODO add your handling code here:
        //panelNorte2.ptAleatorio();
        panelNorte2.pseudoTriangular(1);
    }//GEN-LAST:event_jcbPTRandomActionPerformed

    private void jcbPTSmallestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPTSmallestActionPerformed
        // TODO add your handling code here:
        //panelNorte2.ptGreedy();
        panelNorte2.pseudoTriangular(2);
    }//GEN-LAST:event_jcbPTSmallestActionPerformed

    private void jcbPTHighestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPTHighestActionPerformed
        // TODO add your handling code here:
        //panelNorte2.ptDistMax();
        panelNorte2.pseudoTriangular(3);
    }//GEN-LAST:event_jcbPTHighestActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        panel.cargarImagenPunto(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jcbFlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFlipActionPerformed
        // TODO add your handling code here:
        panelNorte2.flipar(jcbFlip.isSelected());
    }//GEN-LAST:event_jcbFlipActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jcbS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbS1ActionPerformed
        // TODO add your handling code here:
        panelNorte2.polSimple(panelNorte2.MINAREA, panelNorte2.GREEDY, panelNorte2.GREEDY, 1);
    }//GEN-LAST:event_jcbS1ActionPerformed

    private void jcbS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbS2ActionPerformed
        // TODO add your handling code here:
        panelNorte2.polSimple(panelNorte2.MINAREA, panelNorte2.RANDOM, panelNorte2.GREEDY, 2);
    }//GEN-LAST:event_jcbS2ActionPerformed

    private void jcbS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbS3ActionPerformed
        // TODO add your handling code here:
        panelNorte2.polSimple(panelNorte2.MINAREA, panelNorte2.MINAREA, panelNorte2.MINAREA, 3);
    }//GEN-LAST:event_jcbS3ActionPerformed

    private void jcbS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbS4ActionPerformed
        // TODO add your handling code here:
        panelNorte2.polSimple(panelNorte2.RANDOM, panelNorte2.GREEDY, panelNorte2.GREEDY, 4);
    }//GEN-LAST:event_jcbS4ActionPerformed

    private void jcbS5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbS5ActionPerformed
        // TODO add your handling code here:
        panelNorte2.polSimple(panelNorte2.RANDOM, panelNorte2.RANDOM, panelNorte2.GREEDY, 5);
    }//GEN-LAST:event_jcbS5ActionPerformed

    private void jcbS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbS6ActionPerformed
        // TODO add your handling code here:
        panelNorte2.polSimple(panelNorte2.RANDOM, panelNorte2.MINAREA, panelNorte2.MINAREA, 6);
    }//GEN-LAST:event_jcbS6ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        panelNorte2.abrirPuntos();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        panelNorte2.abrirAristas();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        salir(evt);
    }//GEN-LAST:event_formWindowClosing

    private void jcbDilationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDilationActionPerformed
        // TODO add your handling code here:
        panelNorte2.setDilacion(jcbDilation.isSelected());
    }//GEN-LAST:event_jcbDilationActionPerformed

    private void jcbVoronoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVoronoiActionPerformed
        // TODO add your handling code here:
        panelNorte2.setVoronoi(jcbVoronoi.isSelected());
    }//GEN-LAST:event_jcbVoronoiActionPerformed

    private void jcbIsPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbIsPTActionPerformed
        // TODO add your handling code here:
        FV.panel.esPTr();
    }//GEN-LAST:event_jcbIsPTActionPerformed

    private void jcbShowBGImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbShowBGImageActionPerformed
        // TODO add your handling code here:
        panelNorte2.setShowImage(jcbShowBGImage.isSelected());
    }//GEN-LAST:event_jcbShowBGImageActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        VentanaPruebas v = new VentanaPruebas();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        v.setSize(d.height + d.height / 4, d.height - 100);
        v.setLocationRelativeTo(v);
        //v.setExtendedState(JFrame.MAXIMIZED_BOTH);
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        panel.triangulacionAleatoria();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jcbShowImagePointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbShowImagePointsActionPerformed
        // TODO add your handling code here:
        panel.setImagenPunto(jcbShowImagePoints.isSelected());
    }//GEN-LAST:event_jcbShowImagePointsActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
        try {
            File file = new File((getClass().getResource("hervis2013.pdf")).getFile());
            Desktop.getDesktop().open(file);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        panel.guardarImagen(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jcbPainTrianglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPainTrianglesActionPerformed
        // TODO add your handling code here:
        panelNorte2.pintar(jcbPainTriangles.isSelected());
    }//GEN-LAST:event_jcbPainTrianglesActionPerformed

    public static void borrar() {
        panel.borrar();
        panelSur1.reiniciar();
        jcbDilation.setSelected(false);
        jcbFlip.setSelected(false);
        jcbFlip.setEnabled(false);
        btnGT.clearSelection();
        btnGPT.clearSelection();
        btnGP.clearSelection();
        /*jcbTDelaunay.setSelected(false);
        jcbTGreedy.setSelected(false);
        jcbTFan.setSelected(false);
        jcbTIncremental.setSelected(false);
        jcbTDivAndConq.setSelected(false);
        jcbVoronoi.setSelected(false);
        jcbPTRandom.setSelected(false);
        jcbPTSmallest.setSelected(false);
        jcbPTHighest.setSelected(false);
        jcbS1.setSelected(false);
        jcbS2.setSelected(false);
        jcbS3.setSelected(false);
        jcbS4.setSelected(false);
        jcbS5.setSelected(false);
        jcbS6.setSelected(false);*/
        jcbShowBGImage.setSelected(false);
        jcbShowImagePoints.setSelected(false);
        jcbPainTriangles.setSelected(false);
    }

    public void reiniciar() {
        getContentPane().remove(panelNorte2);
        panelNorte2 = new PanelNorte();
        getContentPane().add(panelNorte2, java.awt.BorderLayout.WEST);
        pack();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public static boolean guardar() {
        try {
            return panel.guardarTXT();
        } catch (IOException ex) {
            Logger.getLogger(FV.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    public static void setDirectorio(String d) {
        //File prop = new File("propiedades.prop");
        try {
            FileOutputStream outP = new FileOutputStream(System.getProperty("java.io.tmpdir") + "propiedades.prop");
            properties = new Properties();
            properties.put("dir", d);
            properties.store(outP, null);
            outP.flush();
            outP.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


        /*File zipFile = new File(System.getProperty("user.dir") + File.separator + "Visualizador.jar");
        //JOptionPane.showMessageDialog(null, System.getProperty("user.dir") + File.separator + "Visualizador.jar");
        try {
        File tempFile = new File(zipFile.getName() + ".temp");
        // delete it, otherwise you cannot rename your existing zip to it.
        tempFile.delete();
        
        boolean renameOk = zipFile.renameTo(tempFile);
        if (!renameOk) {
        JOptionPane.showMessageDialog(null, "could not rename the file " + zipFile.getAbsolutePath() + " to " + tempFile.getAbsolutePath());
        }
        byte[] buf = new byte[1024];
        
        ZipInputStream zin;
        
        zin = new ZipInputStream(new FileInputStream(tempFile));
        ZipOutputStream out = new ZipOutputStream(new FileOutputStream(zipFile));
        ZipEntry entry = zin.getNextEntry();
        
        
        while (entry != null) {
        String name = entry.getName();
        boolean notInFiles = true;
        //for (File f : files) {
        if (/*f.getName().equals(name) || name.equals((String) "visLotes/" + "Directorio.txt")) {
        notInFiles = false;
        //break;
        }
        //}
        if (notInFiles) {
        // Add ZIP entry to output stream.
        out.putNextEntry(new ZipEntry(name));
        // Transfer bytes from the ZIP file to the output file
        int len;
        while ((len = zin.read(buf)) > 0) {
        out.write(buf, 0, len);
        }
        }
        entry = zin.getNextEntry();
        }
        // Close the streams        
        zin.close();
        // Compress the files
        //for (int i = 0; i < files.length; i++) {
        JOptionPane.showMessageDialog(null, "Guardó todas las entradas viejas");
        FileWriter fw = new FileWriter("Directorio.txt");
        fw.append(d);
        fw.close();
        File f = new File("Directorio.txt");
        InputStream in = new FileInputStream(f);//FV.class.getClassLoader().getResourceAsStream(propertyFileName);//new FileInputStream(f);
        // Add ZIP entry to output stream.
        out.putNextEntry(new ZipEntry("visLotes/" + f.getName()));
        // Transfer bytes from the file to the ZIP file
        int len;
        while ((len = in.read(buf)) > 0) {
        out.write(buf, 0, len);
        }
        // Complete the entry
        out.closeEntry();
        in.close();
        //}
        // Complete the ZIP file
        out.close();
        tempFile.delete();
        JOptionPane.showMessageDialog(null, "Se debería haber guardado el directorio");
        //f.delete();
        } catch (FileNotFoundException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
        }*/
    }

    public static String getDirectorio() {
        File prop = new File(System.getProperty("java.io.tmpdir") + "propiedades.prop");

        properties = new Properties();
        String directorio = new String();
        try {
            if (!prop.exists()) {
                InputStream is = FV.class.getClassLoader().getResourceAsStream(propertyFileName);
                properties.load(is);
                directorio = (String) properties.get("dir");
            } else {
                FileInputStream is = new FileInputStream(prop);
                properties.load(is);
                directorio = (String) properties.get("dir");
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo leer: " + ex.getMessage(), "Leer archivo", JOptionPane.ERROR_MESSAGE);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo leer: " + ex.getMessage(), "Leer archivo", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error en IO" + ex.getMessage());
        } finally {
            return directorio;
        }

    }
    
    public void salir(WindowEvent evt){
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        if (panel.getL().size() > 0) {
            //Locale.setDefault(Locale.ENGLISH);
            int resp = JOptionPane.showConfirmDialog(null, "¿Save changes?");

            switch (resp) {
                case 0:
                    if (!guardar()) {
                        formWindowClosing(evt);
                    } else {
                        System.exit(0);
                    }
                    break;
                case 1:
                    System.exit(0);
                case -1:
                case 2:  this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                    return;
            }
        } else {
            System.exit(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.ButtonGroup btnGP;
    private static javax.swing.ButtonGroup btnGPT;
    private static javax.swing.ButtonGroup btnGT;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private static javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JCheckBoxMenuItem jcbDilation;
    private static javax.swing.JCheckBoxMenuItem jcbFlip;
    private static javax.swing.JMenuItem jcbIsPT;
    private static javax.swing.JCheckBoxMenuItem jcbPTHighest;
    private static javax.swing.JCheckBoxMenuItem jcbPTRandom;
    private static javax.swing.JCheckBoxMenuItem jcbPTSmallest;
    private static javax.swing.JCheckBoxMenuItem jcbPainTriangles;
    private static javax.swing.JCheckBoxMenuItem jcbS1;
    private static javax.swing.JCheckBoxMenuItem jcbS2;
    private static javax.swing.JCheckBoxMenuItem jcbS3;
    private static javax.swing.JCheckBoxMenuItem jcbS4;
    private static javax.swing.JCheckBoxMenuItem jcbS5;
    private static javax.swing.JCheckBoxMenuItem jcbS6;
    private static javax.swing.JCheckBoxMenuItem jcbShowBGImage;
    private static javax.swing.JCheckBoxMenuItem jcbShowImagePoints;
    private static javax.swing.JCheckBoxMenuItem jcbTDelaunay;
    private static javax.swing.JCheckBoxMenuItem jcbTDivAndConq;
    private static javax.swing.JCheckBoxMenuItem jcbTFan;
    private static javax.swing.JCheckBoxMenuItem jcbTGreedy;
    private static javax.swing.JCheckBoxMenuItem jcbTIncremental;
    private static javax.swing.JCheckBoxMenuItem jcbVoronoi;
    public static visualizador.JPanelDibujo panel;
    public static visualizador.PanelNorte panelNorte2;
    public static visualizador.PanelSur panelSur1;
    // End of variables declaration//GEN-END:variables
}
