/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelSur.java
 *
 * Created on 08/09/2009, 13:22:52
 */

package visualizador;

/**
 *
 * @author Pablazo
 */
public class PanelSur extends javax.swing.JPanel {

    /** Creates new form PanelSur */
    public PanelSur() {
        initComponents();
    }
    public void setTextPeso(String s){
        txtPeso.setText(s);
    }

    public void setTextDilacion (String s){
        txtDilation.setText(s);
    }

    public void setTextCantPT(String s){
        txtCantPT.setText(s);
    }

    public void setTextPosx(String s){
        txtX.setText(s);
    }

    public void setTextPosy(String s){
        txtY.setText(s);
    }

    public void setTextCantP(String s){
        txtPuntos.setText(s);
    }

    public void setTextCantA(String s){
        txtAristas.setText(s);
    }
    public int getTextCantA(){
        return Integer.parseInt(txtAristas.getText());
    }

    public void habilitarT(boolean t){
        //btnBorrar.setEnabled(t);
        txtPeso.setText("0");
        txtCantPT.setText("0");
        txtDilation.setText("0");
        txtPuntos.setText("0");
        txtAristas.setText("0");
        if (!t){
            //lblDilation.setEnabled(t);
            //txtDilation.setEnabled(t);
            habilitarCantPT(t);
        }
    }

    public void habilitarCantPT(boolean b){
        lblCantPT.setEnabled(b);
        txtCantPT.setEnabled(b);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblX = new javax.swing.JLabel();
        lblY = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        txtY = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        lblDilation = new javax.swing.JLabel();
        txtDilation = new javax.swing.JTextField();
        lblCantPT = new javax.swing.JLabel();
        txtCantPT = new javax.swing.JTextField();
        lblPuntos = new javax.swing.JLabel();
        lblAristas = new javax.swing.JLabel();
        txtPuntos = new javax.swing.JTextField();
        txtAristas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jsZoom = new javax.swing.JSlider();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setLayout(new java.awt.GridBagLayout());

        lblX.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblX.setLabelFor(txtX);
        lblX.setText("x:  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(lblX, gridBagConstraints);

        lblY.setLabelFor(txtY);
        lblY.setText("  y:  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(lblY, gridBagConstraints);

        lblPeso.setText("Weight: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(lblPeso, gridBagConstraints);

        txtX.setEditable(false);
        txtX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtX.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(txtX, gridBagConstraints);

        txtY.setEditable(false);
        txtY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtY.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(txtY, gridBagConstraints);

        txtPeso.setEditable(false);
        txtPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPeso.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(txtPeso, gridBagConstraints);

        lblDilation.setText("Dilation:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(lblDilation, gridBagConstraints);

        txtDilation.setEditable(false);
        txtDilation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDilation.setText("0");
        txtDilation.setPreferredSize(new java.awt.Dimension(50, 20));
        txtDilation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDilationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(txtDilation, gridBagConstraints);

        lblCantPT.setText("Total PT:");
        lblCantPT.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(lblCantPT, gridBagConstraints);

        txtCantPT.setEditable(false);
        txtCantPT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantPT.setText("0");
        txtCantPT.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(txtCantPT, gridBagConstraints);

        lblPuntos.setText("Points:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(lblPuntos, gridBagConstraints);

        lblAristas.setText("Edges:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(lblAristas, gridBagConstraints);

        txtPuntos.setEditable(false);
        txtPuntos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntos.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(txtPuntos, gridBagConstraints);

        txtAristas.setEditable(false);
        txtAristas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAristas.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(txtAristas, gridBagConstraints);

        jLabel1.setText("Zoom");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(jLabel1, gridBagConstraints);

        jsZoom.setMinimum(1);
        jsZoom.setPaintLabels(true);
        jsZoom.setPaintTicks(true);
        jsZoom.setSnapToTicks(true);
        jsZoom.setValue(30);
        jsZoom.setMinimumSize(new java.awt.Dimension(200, 31));
        jsZoom.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsZoomStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 19;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(jsZoom, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDilationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDilationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDilationActionPerformed

    private void jsZoomStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsZoomStateChanged
        // TODO add your handling code here:
        FV.panel.setZoom(jsZoom.getValue());
    }//GEN-LAST:event_jsZoomStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jsZoom;
    private javax.swing.JLabel lblAristas;
    private javax.swing.JLabel lblCantPT;
    private javax.swing.JLabel lblDilation;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblY;
    private javax.swing.JTextField txtAristas;
    private javax.swing.JTextField txtCantPT;
    private javax.swing.JTextField txtDilation;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPuntos;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    // End of variables declaration//GEN-END:variables

    /*void activarDilation(boolean selected) {
        lblDilation.setEnabled(selected);
        txtDilation.setEnabled(selected);
    }*/

    /*void reinit(){
        removeAll();
        initComponents();
    }*/

    void reiniciar() {
        txtX.setText("0");
        txtY.setText("0");
        txtPeso.setText("0");
        txtDilation.setText("0");
        txtPuntos.setText("0");
        txtAristas.setText("0");
        txtCantPT.setText("0");
        txtCantPT.setEnabled(false);
        lblCantPT.setEnabled(false);
        jsZoom.setValue(30);
        FV.panel.setZoom(jsZoom.getValue());
    }
}
