/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TituloPrueba.java
 *
 * Created on 06/08/2010, 11:24:31
 */

package visualizador;

/**
 *
 * @author Pablazo
 */
public class TituloPrueba extends javax.swing.JPanel {

    /** Creates new form TituloPrueba */
    public TituloPrueba() {
        initComponents();
    }

    public void setTitulo(String t){
        jlblTitulo.setText(t);
    }

    public void setIntento(String t){
        jlblIntento.setText(t);
    }

    public void setDatos(String t){
        jlblDatos.setText(t);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitulo = new javax.swing.JLabel();
        jlblIntento = new javax.swing.JLabel();
        jlblDatos = new javax.swing.JLabel();

        jlblTitulo.setText("Título:");

        jlblIntento.setText("Intento:");

        jlblDatos.setText("Datos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblIntento)
                    .addComponent(jlblTitulo)
                    .addComponent(jlblDatos))
                .addContainerGap(528, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlblTitulo)
                .addGap(13, 13, 13)
                .addComponent(jlblIntento)
                .addGap(18, 18, 18)
                .addComponent(jlblDatos)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblDatos;
    private javax.swing.JLabel jlblIntento;
    private javax.swing.JLabel jlblTitulo;
    // End of variables declaration//GEN-END:variables

}
